project:
  type: website
  output-dir: docs

website:
  title: "GRDI-AMR"
  navbar:
    left:
      - about.qmd
      - project.qmd
      - publications.qmd
      - softwaretools.qmd
      - text: "News"
        href: news.qmd
      - links.qmd


format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: source

