project:
  type: website
  output-dir: docs

website:
  title: "GRDI-AMR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
      - publications.qmd
      - softwaretools.qmd
      - links.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: source

